sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
# Install AWS CLI for uploading storybook to S3.
before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
install:
  - yarn
script:
  - npm run lint
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - semantic-release
  # Deploy storybook demo to S3: https://s3.amazonaws.com/transitive.js/index.html
  - yarn deploy-storybook
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
