sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
# Install AWS CLI for uploading storybook to S3.
before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  # add aws 'default' profile for uploading storybook
  - mkdir ~/.aws && printf '%s\n' '[default]' 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}' 'region=us-east-1' > ~/.aws/config
install:
  - yarn
script:
  - npm run lint
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - semantic-release
  # Deploy storybook demo to S3: https://s3.amazonaws.com/transitive.js/index.html
  - yarn deploy-storybook
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
