sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
install:
  - yarn
script:
  - npm run lint
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - semantic-release
  - yarn deploy-storybook --out=demo
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
